import Foundation

/// Generates the QuickJS driver `ffedit` runs.
///
/// `ffedit` calls `glitch_frame(frame)` once per frame, in stream order,
/// starting at frame 0 — confirmed by round-tripping a 240-frame clip and
/// checking the JSON export has exactly 240 entries in the same order the AVI
/// engine sees them. That means a plain incrementing counter is all a script
/// needs to know which frame it is currently holding, which is what lets the
/// dispatch table below be a flat array indexed by frame number rather than
/// anything stateful on the JS side.
public enum VectorEngine {
    /// One shared driver: a per-frame dispatch table (computed in Swift from
    /// the same trigger/rule pipeline the AVI engine uses) plus one function
    /// per effect, ported from the DMP scripts. `amount` replaces each
    /// script's hardcoded constant.
    public static func generateScript(ops: [VectorOp], frameCount: Int) -> String {
        // Frame -> (kind, amount), flattened so the JS side does no range
        // search. Frames with no op are simply absent from the table.
        var table = [String](repeating: "null", count: frameCount)
        for op in ops.sorted(by: { $0.startFrame < $1.startFrame }) {
            let lo = max(0, op.startFrame)
            let hi = min(frameCount, op.endFrame)
            guard lo < hi else { continue }
            let entry = "[\"\(op.kind.rawValue)\",\(op.amount),\(op.seed)]"
            for i in lo ..< hi { table[i] = entry }
        }
        let tableJS = "[" + table.joined(separator: ",") + "]"

        return """
        // Generated by Beygla — VectorEngine.generateScript. Do not hand-edit;
        // regenerate from the project instead.
        \(effectFunctions)

        var OPS = \(tableJS);
        var frameIndex = 0;

        export function glitch_frame(frame) {
            let entry = OPS[frameIndex];
            frameIndex++;
            if (entry === null) return;

            let mvs = frame["mv"];
            if (!mvs) return;
            let fwd = mvs["forward"];
            if (!fwd) return;

            let kind = entry[0], amount = entry[1], seed = entry[2];
            let fn = EFFECTS[kind];
            if (fn) fn(fwd, amount, seed);

            // A vector outside the range the frame's own fcode can encode
            // does not fail cleanly — ffedit clamps it, but the encoder
            // still reports the macroblock as "damaged" on decode, which
            // shows up as a handful of corrupted blocks scattered through an
            // otherwise correct picture. mv.fcode is exactly the range
            // MPEG-4 allows for this frame, so clamp to it explicitly rather
            // than relying on ffedit's own fallback.
            let fcode = (mvs["fcode"] && mvs["fcode"][0]) || 1;
            let limit = (1 << (fcode + 4)) - 1;
            for (let i = 0; i < fwd.length; i++) {
                let row = fwd[i];
                for (let j = 0; j < row.length; j++) {
                    let mv = row[j];
                    if (mv[0] > limit) mv[0] = limit; else if (mv[0] < -limit - 1) mv[0] = -limit - 1;
                    if (mv[1] > limit) mv[1] = limit; else if (mv[1] < -limit - 1) mv[1] = -limit - 1;
                }
            }
        }
        """
    }

    /// One JS function per `VectorOpKind`, each taking the raw `forward`
    /// vector grid plus `amount` (0...1) and, where the effect needs
    /// determinism, a per-op `seed`.
    private static let effectFunctions = """
    // A tiny seeded PRNG (mulberry32) so vibrate is reproducible per op rather
    // than reading Math.random() and differing between renders of the same
    // project.
    function rng(seed) {
        return function () {
            seed |= 0; seed = (seed + 0x6D2B79F5) | 0;
            let t = Math.imul(seed ^ (seed >>> 15), 1 | seed);
            t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
            return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
        };
    }

    function sink(fwd, amount, seed) {
        // Amount 0 -> demanding threshold (only the fastest blocks freeze);
        // amount 1 -> almost everything does.
        let threshold = 14 * (1 - amount) + 0.5;
        let t2 = threshold * threshold;
        for (let i = 0; i < fwd.length; i++) {
            let row = fwd[i];
            for (let j = 0; j < row.length; j++) {
                let mv = row[j];
                if (mv[0] * mv[0] + mv[1] * mv[1] > t2) { mv[0] = 0; mv[1] = 0; }
            }
        }
    }

    function stop(fwd, amount, seed) {
        for (let i = 0; i < fwd.length; i++) {
            let row = fwd[i];
            for (let j = 0; j < row.length; j++) { row[j][0] = 0; row[j][1] = 0; }
        }
    }

    function invertReverse(fwd, amount, seed) {
        for (let i = 0; i < fwd.length; i++) {
            let row = fwd[i];
            for (let j = 0; j < row.length; j++) {
                let mv = row[j];
                mv[0] = -mv[0]; mv[1] = -mv[1];
            }
        }
    }

    function mirror(fwd, amount, seed) {
        let copy = JSON.parse(JSON.stringify(fwd));
        for (let i = 0; i < fwd.length; i++) {
            let row = fwd[i], src = copy[i];
            let w = row.length;
            for (let j = 0; j < w; j++) {
                let s = src[(w - 1) - j];
                row[j][0] = -s[0];
                row[j][1] = s[1];
            }
        }
    }

    function vibrate(fwd, amount, seed) {
        let next = rng(seed >>> 0);
        let range = 2 + amount * 30;
        let bias = range / 2;
        for (let i = 0; i < fwd.length; i++) {
            let row = fwd[i];
            for (let j = 0; j < row.length; j++) {
                let mv = row[j];
                mv[0] += Math.floor(next() * range - bias);
                mv[1] += Math.floor(next() * range - bias);
            }
        }
    }

    // Shared by zoom, slamZoom and shear: a field that varies with distance
    // from the frame's centre.
    function radial(fwd, amount, seed, replace, diagonal) {
        let h = fwd.length, w = fwd[0] ? fwd[0].length : 0;
        if (w === 0) return;
        let cy = h / 2, cx = w / 2;
        // Bipolar around amount=0.5 so the low half of the knob pulls inward
        // and the high half pushes outward; clamped against the frame's own
        // fcode range afterward, so this can be pushed hard without risking
        // the macroblock corruption an unclamped value would cause.
        let strength = amount * 90 - 45;
        for (let i = 0; i < h; i++) {
            let row = fwd[i];
            for (let j = 0; j < w; j++) {
                let mv = row[j];
                let dx, dy;
                if (diagonal) {
                    dx = ((i - cx) / 100) * strength;
                    dy = ((j - cy) / 100) * strength;
                } else {
                    dx = ((cx - j) / 100) * strength;
                    dy = ((cy - i) / 100) * strength;
                }
                if (replace) { mv[0] = dx; mv[1] = dy; }
                else { mv[0] += dx; mv[1] += dy; }
            }
        }
    }
    function zoom(fwd, amount, seed) { radial(fwd, amount, seed, false, false); }
    function slamZoom(fwd, amount, seed) { radial(fwd, amount, seed, true, false); }
    function shear(fwd, amount, seed) { radial(fwd, amount, seed, false, true); }

    // Delay keeps its own ring buffer per delay length. Frames before the
    // buffer fills pass through untouched — there is nothing to delay from
    // yet — rather than showing a false, empty vector field.
    var delayBuffers = {};
    function delay(fwd, amount, seed) {
        let length = Math.max(2, Math.round(2 + amount * 28));
        let feedback = amount > 0.5 ? (amount - 0.5) * 2 : 0;
        let key = String(seed);
        let buf = delayBuffers[key];
        if (!buf) { buf = []; delayBuffers[key] = buf; }

        let copy = JSON.parse(JSON.stringify(fwd));
        buf.push(copy);
        if (buf.length > length) buf.shift();
        if (buf.length < length) return; // not warmed up yet

        let past = buf[0];
        for (let i = 0; i < fwd.length; i++) {
            let row = fwd[i], prow = past[i];
            for (let j = 0; j < row.length; j++) {
                let mv = row[j], pmv = prow[j];
                let x = mv[0], y = mv[1];
                mv[0] = pmv[0]; mv[1] = pmv[1];
                if (feedback > 0) { pmv[0] = pmv[0] * feedback + x; pmv[1] = pmv[1] * feedback + y; }
            }
        }
    }

    // Shift accumulates a per-block vertical carry across frames, the way
    // gravity keeps adding to a falling object's speed rather than resetting
    // it each frame.
    var shiftCarry = {};
    function shift(fwd, amount, seed) {
        let g = amount * 6;
        let key = String(seed);
        let carry = shiftCarry[key];
        if (!carry) {
            carry = [];
            for (let i = 0; i < fwd.length; i++) carry.push(new Array(fwd[i].length).fill(0));
            shiftCarry[key] = carry;
        }
        for (let i = 0; i < fwd.length; i++) {
            let row = fwd[i], crow = carry[i];
            for (let j = 0; j < row.length; j++) {
                let mv = row[j];
                let next = mv[1];
                mv[1] = crow[j];
                crow[j] = next + crow[j] + g;
            }
        }
    }

    function noise(fwd, amount, seed) {
        let largest = 0;
        for (let i = 0; i < fwd.length; i++) {
            let row = fwd[i];
            for (let j = 0; j < row.length; j++) {
                let mv = row[j];
                let m = mv[0] * mv[0] + mv[1] * mv[1];
                if (m > largest) largest = m;
            }
        }
        if (largest === 0) return;
        let cutoff = largest * 0.5;
        let multiple = 2 + amount * 18;
        for (let i = 0; i < fwd.length; i++) {
            let row = fwd[i];
            for (let j = 0; j < row.length; j++) {
                let mv = row[j];
                let m = mv[0] * mv[0] + mv[1] * mv[1];
                if (m < cutoff) { mv[0] *= multiple; mv[1] *= multiple; }
            }
        }
    }

    var EFFECTS = {
        sink: sink, stop: stop, invertReverse: invertReverse, mirror: mirror,
        vibrate: vibrate, zoom: zoom, slamZoom: slamZoom, shear: shear,
        delay: delay, shift: shift, noise: noise,
    };
    """
}
